config/routes.rb
Rails.application.routes.draw do
  
resources :animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  end

  def show
    @animal = Animal.find(params[:id])
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)

    if @animal.save
      redirect_to animals_path
    else
    render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to animals_path
    else
      render :edit
    end
  end

def destroy
  Animal.find(params[:id]).destroy
  redirect_to animals_path
  

end

  private

    def animal_params
      params.require(:animal).permit(:name, :age, :hair_color, :eye_color, :gender, :alive)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.erb
<%= form_for @animal do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
  
    <%= f.label :age %>
    <%= f.text_field :age %>
  
    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>
  
    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>
  
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  
    <%= f.label :alive %>
    <%= f.text_field :alive %>
    <%# <%= f.select :alive, [ 'Yes', 'No' ], :prompt => 'Select One' %>
  
    <%= f.submit %>
  <% end %>

app/views/animals/edit.html.erb
<h1>Edit Animal</h1>
<%= render 'animals/form' %>

app/views/animals/index.html.erb
<h1>All the Animals</h1>
<%= link_to 'Add Animal', new_animal_path %>
<% @animals.each do |animal| %>
    <%= animal.name %>
    <%= link_to 'Show Animal', animal_path(animal.id) %>
    <%= link_to 'Delete', animal_path(animal.id), method: :delete %>
    <% end %>

app/views/animals/new.html.erb
<h1>Add Animal</h1>
<%= render 'animals/form' %>

app/views/animals/show.html.erb
<h1>Animals#show</h1>
<%= @animal.id %>
<%= @animal.name %>
<%= @animal.age %>
<%= link_to 'Go Back', animals_path %>
<%= link_to 'Edit', edit_animal_path(@animal.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Person</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>